//===- AttrCodeGen.cpp - Attribute code generation backends -----*- C++ -*-===//
//
// Part of the CUDA Tile IR project, under the Apache License v2.0 with LLVM
// Exceptions. See https://llvm.org/LICENSE.txt for license information.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// TableGen backends for generating .inc files from CudaTile attribute and
// architecture definitions:
//   -gen-enum-attr-list       X-macro list of enum attr wrappers
//   -gen-gpu-arch-def         X-macro list of GPU architectures
//   -gen-gpu-arch-constants   list per-family SM constants and CC ranges
//   -gen-hint-key-accessors   X-macro list of optimization hint key accessors
//
//===----------------------------------------------------------------------===//

#include "AttrCodeGen.h"

#include "mlir/TableGen/GenInfo.h"

#include "llvm/ADT/StringRef.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TableGen/Error.h"
#include "llvm/TableGen/Record.h"

#include <map>
#include <string>
#include <vector>

using namespace llvm;
using namespace mlir;
using namespace cudatile::tblgen;

// ---------------------------------------------------------------------------
// Shared helpers (implementations for AttrCodeGen.h)
// ---------------------------------------------------------------------------

namespace cudatile {
namespace tblgen {

bool isCudaTileEnumDef(const RecordKeeper &records, const Record *rec) {
  const Record *base = records.getClass("CudaTileI32EnumAttr");
  return base && rec->isSubClassOf(base);
}

bool hasI32EnumWithCases(const Record *rec) {
  auto *enumField = rec->getValue("enum");
  if (!enumField) {
    return false;
  }
  auto *enumDef = rec->getValueAsDef("enum");
  if (!enumDef) {
    return false;
  }
  return enumDef->getValue("enumerants") != nullptr;
}

bool isCudaTileEnumAttrWrapper(const RecordKeeper &records, const Record *rec) {
  const Record *base = records.getClass("CudaTileEnumAttr");
  if (base && rec->isSubClassOf(base)) {
    return hasI32EnumWithCases(rec);
  }

  const Record *enumAttr = records.getClass("EnumAttr");
  if (!enumAttr || !rec->isSubClassOf(enumAttr)) {
    return false;
  }
  auto *dialect = rec->getValueAsDef("dialect");
  if (!dialect || dialect->getName() != "CudaTile_Dialect") {
    return false;
  }
  return hasI32EnumWithCases(rec);
}

std::vector<std::pair<std::string, std::string>>
getEnumCases(const Record *enumDef) {
  std::vector<std::pair<std::string, std::string>> cases;
  for (const auto *c : enumDef->getValueAsListOfDefs("enumerants")) {
    std::string str = c->getValueAsString("str").trim().str();
    std::string sym = c->getValueAsString("symbol").str();
    cases.emplace_back(std::move(str), std::move(sym));
  }
  return cases;
}

std::optional<EnumAttrInfo> extractEnumAttrInfo(const RecordKeeper &records,
                                                const Record *wrapperRec) {
  const Record *enumInfo = wrapperRec->getValueAsDef("enum");
  if (!enumInfo) {
    return std::nullopt;
  }

  EnumAttrInfo info;
  info.enumDef = enumInfo;
  info.enumClass = enumInfo->getValueAsString("className").str();
  info.attrClass = info.enumClass + "Attr";
  info.jsonKey = wrapperRec->getValueAsString("mnemonic").str();
  return info;
}

} // namespace tblgen
} // namespace cudatile

// ---------------------------------------------------------------------------
// Local helpers
// ---------------------------------------------------------------------------

static const Record *findEnumByClassName(const RecordKeeper &records,
                                         StringRef className) {
  for (const auto &def : records.getDefs()) {
    if (!isCudaTileEnumDef(records, def.second.get())) {
      continue;
    }
    if (def.second->getValueAsString("className") == className) {
      return def.second.get();
    }
  }
  return nullptr;
}

// ---------------------------------------------------------------------------
// -gen-enum-attr-list
// ---------------------------------------------------------------------------

static bool genEnumAttrList(const RecordKeeper &records, raw_ostream &os) {
  os << "// This file is auto-generated by cuda-tile-tblgen "
        "-gen-enum-attr-list.\n";
  os << "// Do not edit.\n\n";
  os << "#ifndef CUDA_TILE_ENUM_ATTR\n";
  os << "#define CUDA_TILE_ENUM_ATTR(JsonKey, AttrType, EnumType)\n";
  os << "#endif\n\n";

  std::vector<EnumAttrInfo> infos;
  for (const auto &def : records.getDefs()) {
    if (isCudaTileEnumAttrWrapper(records, def.second.get())) {
      if (auto info = extractEnumAttrInfo(records, def.second.get())) {
        infos.push_back(*info);
      }
    }
  }

  llvm::sort(infos, [](const EnumAttrInfo &a, const EnumAttrInfo &b) {
    return a.jsonKey < b.jsonKey;
  });

  for (const auto &info : infos) {
    os << formatv("CUDA_TILE_ENUM_ATTR(\"{0}\", {1}, {2})\n", info.jsonKey,
                  info.attrClass, info.enumClass);
  }

  os << "\n#undef CUDA_TILE_ENUM_ATTR\n";
  return false;
}

// ---------------------------------------------------------------------------
// -gen-gpu-arch-def
// ---------------------------------------------------------------------------

static bool genGpuArchDef(const RecordKeeper &records, raw_ostream &os) {
  const Record *gpuArchEnum = findEnumByClassName(records, "GpuArchitecture");
  if (!gpuArchEnum) {
    os << "// ERROR: CudaTile_GpuArchitecture enum not found.\n";
    return true;
  }

  auto cases = gpuArchEnum->getValueAsListOfDefs("enumerants");
  if (cases.empty()) {
    os << "// ERROR: GpuArchitecture enum has no cases.\n";
    return true;
  }

  os << "// Each consumer #defines CUDA_TILE_GPU_ARCH(Sym, IntVal, Str)\n";
  os << "// before including this file.  Optionally define\n";
  os << "// CUDA_TILE_GPU_ARCH_FIRST for the first entry (defaults to\n";
  os << "// CUDA_TILE_GPU_ARCH) to avoid trailing-comma issues in\n";
  os << "// function argument lists.\n\n";
  os << "#ifndef CUDA_TILE_GPU_ARCH\n";
  os << "#define CUDA_TILE_GPU_ARCH(Sym, IntVal, Str)\n";
  os << "#endif\n\n";
  os << "#ifndef CUDA_TILE_GPU_ARCH_FIRST\n";
  os << "#define CUDA_TILE_GPU_ARCH_FIRST(Sym, IntVal, Str)                    "
        "         \\\n";
  os << "  CUDA_TILE_GPU_ARCH(Sym, IntVal, Str)\n";
  os << "#endif\n\n";

  for (size_t i = 0; i < cases.size(); ++i) {
    std::string str = cases[i]->getValueAsString("str").trim().str();
    int64_t val = cases[i]->getValueAsInt("value");
    bool isFirst = (i == 0);

    os << formatv("{0}({1}, {2}, \"{3}\")\n",
                  isFirst ? "CUDA_TILE_GPU_ARCH_FIRST" : "CUDA_TILE_GPU_ARCH",
                  str, val, str);
  }

  os << "\n#undef CUDA_TILE_GPU_ARCH\n";
  os << "#undef CUDA_TILE_GPU_ARCH_FIRST\n";
  return false;
}

// ---------------------------------------------------------------------------
// -gen-gpu-arch-constants
// ---------------------------------------------------------------------------

static bool genGpuArchConstants(const RecordKeeper &records, raw_ostream &os) {
  const Record *gpuArchEnum = findEnumByClassName(records, "GpuArchitecture");
  if (!gpuArchEnum) {
    os << "// ERROR: CudaTile_GpuArchitecture enum not found.\n";
    return true;
  }

  auto cases = gpuArchEnum->getValueAsListOfDefs("enumerants");

  struct ArchEntry {
    std::string str;
    int64_t val;
  };
  std::vector<std::string> familyOrder;
  std::map<std::string, std::vector<ArchEntry>> familyMap;

  for (const auto *c : cases) {
    std::string family = "Unknown";
    if (c->getValue("archFamily")) {
      family = c->getValueAsString("archFamily").str();
    }

    ArchEntry entry;
    entry.str = c->getValueAsString("str").trim().str();
    entry.val = c->getValueAsInt("value");
    if (familyMap.find(family) == familyMap.end()) {
      familyOrder.push_back(family);
    }
    familyMap[family].push_back(entry);
  }

  os << "// Auto-generated by cuda-tile-tblgen -gen-gpu-arch-constants\n";
  os << "// from CudaTile_GpuArchitecture enum in AttrDefs.td.\n";
  os << "// Do not edit.\n\n";

  for (const auto &family : familyOrder) {
    const auto &entries = familyMap[family];

    os << "static constexpr int32_t k" << family
       << "CCMin = " << entries.front().val << ";\n";

    for (const auto &e : entries) {
      os << "static constexpr int32_t k" << family << "Sm" << e.val << " = "
         << e.val << ";\n";
    }

    os << "static constexpr int32_t k" << family
       << "CCMax = " << entries.back().val << ";\n";

    os << "\n";
  }

  return false;
}

// ---------------------------------------------------------------------------
// -gen-hint-key-accessors
// ---------------------------------------------------------------------------

static bool genHintKeyAccessors(const RecordKeeper &records, raw_ostream &os) {
  const Record *hintKeyEnum = findEnumByClassName(records, "HintKey");
  if (!hintKeyEnum) {
    os << "// ERROR: CudaTile_HintKey enum not found.\n";
    return true;
  }

  os << R"(// Auto-generated by cuda-tile-tblgen -gen-hint-key-accessors.
// Do not edit.

#ifndef CUDA_TILE_HINT_KEY
#define CUDA_TILE_HINT_KEY(Name, Str, RetType, Version)
#endif

)";

  for (const auto *c : hintKeyEnum->getValueAsListOfDefs("enumerants")) {
    std::string sym = c->getValueAsString("symbol").str();
    std::string str = c->getValueAsString("str").trim().str();
    std::string version = c->getValueAsString("sinceVersion").str();

    std::string retType = "int";
    if (c->getValue("hintReturnType")) {
      retType = c->getValueAsString("hintReturnType").str();
    }

    os << formatv("CUDA_TILE_HINT_KEY({0}, \"{1}\", {2}, \"{3}\")\n", sym, str,
                  retType, version);
  }

  os << "\n#undef CUDA_TILE_HINT_KEY\n";
  return false;
}

// ---------------------------------------------------------------------------
// -gen-hint-key-impl
// ---------------------------------------------------------------------------

/// Per-architecture range override for a hint key.
/// Narrows the valid range for specific GPU architecture families.
struct ArchOverrideInfo {
  std::vector<std::string> families; // e.g. ["Ampere", "Ada"]
  int64_t min;
  int64_t max;
};

/// Complete metadata for one hint key, extracted from CudaTileHintKeyCase.
/// Used by -gen-hint-key-impl to generate validators and op-to-key mapping.
struct HintKeyInfo {
  std::string sym;       // C++ enum name and accessor suffix (e.g. "Latency")
  std::string str;       // MLIR string representation (e.g. "latency")
  std::string retType;   // Return type (e.g. "int", "bool")
  std::string validKind; // Validation strategy: "int_range", "pow2_range",
                         // "bool", or "string"
  int64_t validMin = 0;
  int64_t validMax = 0;
  std::vector<std::string> validForOps; // Op class names this hint applies to
  std::vector<ArchOverrideInfo> archOverrides;
};

/// Collect family -> SM prefix mappings from the GpuArchitecture enum.
static std::map<std::string, std::vector<std::string>>
collectFamilySmPrefixes(const RecordKeeper &records) {
  std::map<std::string, std::vector<std::string>> result;
  const Record *gpuArchEnum = findEnumByClassName(records, "GpuArchitecture");
  if (!gpuArchEnum) {
    return result;
  }
  for (const auto *c : gpuArchEnum->getValueAsListOfDefs("enumerants")) {
    std::string family = "Unknown";
    if (c->getValue("archFamily")) {
      family = c->getValueAsString("archFamily").str();
    }
    std::string str = c->getValueAsString("str").trim().str();
    result[family].push_back(str);
  }
  return result;
}

static std::vector<HintKeyInfo>
collectHintKeyInfos(const RecordKeeper &records) {
  const Record *hintKeyEnum = findEnumByClassName(records, "HintKey");
  if (!hintKeyEnum) {
    return {};
  }

  std::vector<HintKeyInfo> infos;
  for (const auto *c : hintKeyEnum->getValueAsListOfDefs("enumerants")) {
    HintKeyInfo info;
    info.sym = c->getValueAsString("symbol").str();
    info.str = c->getValueAsString("str").trim().str();
    info.retType = c->getValue("hintReturnType")
                       ? c->getValueAsString("hintReturnType").str()
                       : "int";
    info.validKind = c->getValue("hintValidationKind")
                         ? c->getValueAsString("hintValidationKind").str()
                         : "int_range";
    if (c->getValue("hintValidMin")) {
      info.validMin = c->getValueAsInt("hintValidMin");
    }
    if (c->getValue("hintValidMax")) {
      info.validMax = c->getValueAsInt("hintValidMax");
    }
    if (c->getValue("hintValidForOps")) {
      for (auto s : c->getValueAsListOfStrings("hintValidForOps")) {
        info.validForOps.push_back(s.str());
      }
    }
    if (c->getValue("hintArchOverrides")) {
      for (const auto *ovr : c->getValueAsListOfDefs("hintArchOverrides")) {
        ArchOverrideInfo aoi;
        for (auto f : ovr->getValueAsListOfStrings("archFamilies")) {
          aoi.families.push_back(f.str());
        }
        aoi.min = ovr->getValueAsInt("overrideMin");
        aoi.max = ovr->getValueAsInt("overrideMax");
        info.archOverrides.push_back(std::move(aoi));
      }
    }
    infos.push_back(std::move(info));
  }
  return infos;
}

static bool genHintKeyImpl(const RecordKeeper &records, raw_ostream &os) {
  auto infos = collectHintKeyInfos(records);
  if (infos.empty()) {
    os << "// ERROR: CudaTile_HintKey enum not found or empty.\n";
    return true;
  }

  auto familyPrefixes = collectFamilySmPrefixes(records);

  os << R"(// Auto-generated by cuda-tile-tblgen -gen-hint-key-impl.
// Do not edit.
//
// This file is #included in Attributes.cpp and provides:
//   1. Validator functions for all hints (int_range, pow2_range, bool, string)
//   2. verifyWithOp op-to-key mapping
// Getter definitions and verifier dispatch use template helpers
// in Attributes.cpp with HintKeyAccessors.inc.

#ifdef CUDA_TILE_HINT_VALIDATORS
// ---- Auto-generated validators ----

)";
  for (const auto &info : infos) {
    if (info.validKind == "bool") {
      os << formatv(R"(static ValidationResult<bool> validate{0}(
    Attribute attr, StringRef context) {{
  auto boolAttr = dyn_cast_or_null<BoolAttr>(attr);
  if (!boolAttr)
    return {{std::nullopt, ("boolean value expected for " + context + "." +
                           stringifyHintKey(HintKey::{0})).str()};
  return {{boolAttr.getValue(), ""};
}

)",
                    info.sym);
    } else if (info.validKind == "int_range" ||
               info.validKind == "pow2_range") {
      os << formatv(R"(static ValidationResult<int64_t> validate{0}(
    Attribute attr, StringRef context) {{
  auto intAttr = dyn_cast_or_null<IntegerAttr>(attr);
  if (!intAttr)
    return {{std::nullopt, ("integer value expected for " + context + "." +
                           stringifyHintKey(HintKey::{0})).str()};
  int64_t val = intAttr.getInt();
  int64_t lo = {1}, hi = {2};
)",
                    info.sym, info.validMin, info.validMax);

      for (const auto &ovr : info.archOverrides) {
        std::string condition;
        for (const auto &fam : ovr.families) {
          auto it = familyPrefixes.find(fam);
          if (it == familyPrefixes.end()) {
            PrintWarning("arch override references unknown family '" + fam +
                         "' in hint key '" + info.sym + "'");
            continue;
          }
          for (const auto &prefix : it->second) {
            if (!condition.empty()) {
              condition += " ||\n      ";
            }
            condition += "context.starts_with(\"" + prefix + "\")";
          }
        }
        if (condition.empty()) {
          continue;
        }
        os << "  if (" << condition << ") {\n";
        os << "    lo = " << ovr.min << "; hi = " << ovr.max << ";\n";
        os << "  }\n";
      }

      if (info.validKind == "pow2_range") {
        os << formatv(R"(  if (val <= 0 || (val & (val - 1)) != 0)
    return {{std::nullopt, ("power-of-2 expected for " + context + "." +
                           stringifyHintKey(HintKey::{0})).str()};
)",
                      info.sym);
      }

      os << formatv(R"(  if (val < lo || val > hi) {{
    int64_t clamped = std::clamp(val, lo, hi);
    return {{clamped, ("value " + Twine(val) + " clamped to " + Twine(clamped) +
                      " for " + context + "." +
                      stringifyHintKey(HintKey::{0})).str()};
  }
  return {{val, ""};
}

)",
                    info.sym);
    } else if (info.validKind == "string") {
      os << formatv(R"(static ValidationResult<std::string> validate{0}(
    Attribute attr, StringRef context) {{
  auto strAttr = dyn_cast_or_null<StringAttr>(attr);
  if (!strAttr)
    return {{std::nullopt, ("string value expected for " + context + "." +
                           stringifyHintKey(HintKey::{0})).str()};
  return {{std::string(strAttr.getValue()), ""};
}

)",
                    info.sym);
    }
  }

  os << "#endif // CUDA_TILE_HINT_VALIDATORS\n\n";

  // Getter definitions and verifier dispatch are handled by template helpers
  // in Attributes.cpp using HintKeyAccessors.inc — not generated here.

  // --- Section 2: verifyWithOp op-to-key mapping ---
  // Build a map: op name -> list of hint key stringified names
  std::map<std::string, std::vector<std::string>> opToKeys;
  for (const auto &info : infos) {
    for (const auto &opName : info.validForOps) {
      opToKeys[opName].push_back("stringifyHintKey(HintKey::" + info.sym + ")");
    }
  }

  os << R"(// ---- Auto-generated op-to-hint-key mapping ----
// Use: paste this block inside verifyWithOp to build keysValidForOperation.
// Guarded by CUDA_TILE_HINT_OP_KEYS.
#ifdef CUDA_TILE_HINT_OP_KEYS
)";
  for (const auto &[opName, keys] : opToKeys) {
    os << "    if (isa<" << opName << ">(op)) {\n";
    for (const auto &key : keys) {
      os << "      keysValidForOperation.push_back(" << key << ");\n";
    }
    os << "    }\n";
  }
  os << "#endif // CUDA_TILE_HINT_OP_KEYS\n";

  return false;
}

// ---------------------------------------------------------------------------
// Registration
// ---------------------------------------------------------------------------

static mlir::GenRegistration genEnumAttrListReg(
    "gen-enum-attr-list",
    "Generate a .inc file with X-macro entries for each CudaTile enum "
    "attribute wrapper",
    [](const RecordKeeper &records, raw_ostream &os) {
      return genEnumAttrList(records, os);
    });

static mlir::GenRegistration genGpuArchDefReg(
    "gen-gpu-arch-def",
    "Generate a .def-style .inc file with X-macro entries for each GPU "
    "architecture (consumed by C/C++ assembler headers)",
    [](const RecordKeeper &records, raw_ostream &os) {
      return genGpuArchDef(records, os);
    });

static mlir::GenRegistration genGpuArchConstantsReg(
    "gen-gpu-arch-constants",
    "Generate a .inc file with per-family SM constants and CC ranges ",
    [](const RecordKeeper &records, raw_ostream &os) {
      return genGpuArchConstants(records, os);
    });

static mlir::GenRegistration genHintKeyAccessorsReg(
    "gen-hint-key-accessors",
    "Generate a .inc file with X-macro entries for each optimization hint key "
    "(accessors for OptimizationHintsAttr)",
    [](const RecordKeeper &records, raw_ostream &os) {
      return genHintKeyAccessors(records, os);
    });

static mlir::GenRegistration genHintKeyImplReg(
    "gen-hint-key-impl",
    "Generate a .inc file with validator functions, getter definitions, "
    "verifier dispatch, and op-to-key mapping for optimization hints",
    [](const RecordKeeper &records, raw_ostream &os) {
      return genHintKeyImpl(records, os);
    });
